
text = """You are a helpful AI assistant. You are a maze solver. Find the shortest path from start to end. Solve this maze by finding a path from S to E.\n\n    Maze:\n    ###########\n    #         #\n    ### ##### #\n    # # #   #S#\n    # ##### # #\n    # # # #   #\n    # # # # ###\n    #    E    #\n    ####### ###\n    #         #\n    ###########\n\n    S - [3,9]\n    E - [7,5]\n\n    Legend:\n    - S = Start position\n    - E = End position  \n    - # = Wall (cannot pass through)\n\n    Rules:\n    - You can only move up, down, left, or right (no diagonal moves)\n    - You cannot pass through walls (#)\n    - Provide the solution as a list of coordinates\n\n    Output format:\n    [[row, col], [row, col], ...]\n\n    For example: [[0, 0], [0, 1], [1, 1], [1, 2]]\n\n    Solution: To solve the maze, we can use a simple algorithm like depth-first search (DFS) or breadth-first search (BFS). Here, I'll use BFS to find the shortest path from S to E.\n\n    Maze:\n    ###########\n    #         #\n    ### ##### #\n    # # #   #S#\n    # ##### # #\n    # # # #   #\n    # # # # ###\n    #    E    #\n    ####### ###\n    #         #\n    ###########\n\n    S - [3,9]\n    E - [7,5]\n\n    Legend:\n    - S = Start position\n    - E = End position  \n    - # = Wall (cannot pass through)\n\n    Rules:\n    - You can only move up, down, left, or right (no diagonal moves)\n    - You cannot pass through walls (#)\n    - Provide the solution as a list of coordinates\n\n    Output format:\n    [[row, col], [row, col], ...]\n\n    For example: [[0, 0], [0, 1], [1, 1], [1, 2]]\n\n    Solution:\n\n    Using BFS, we can find the shortest path from S to E:\n\n    [[3, 9], [3, 8], [3, 7], [3, 6], [3, 5], [4, 5], [4, 6], [4, 7], [4, 8], [5, 8], [5, 7], [5, 6], [6, 6], [6, 5], [6, 4], [7, 4], [7, 5]]\n\n   
 This path has 16 steps and is the shortest path from S to E."""

paths = re.findall(
    r'\[\s*\[\s*\d+\s*,\s*\d+\s*\](?:\s*,\s*\[\s*\d+\s*,\s*\d+\s*\])*\s*\]',
    text
)
paths = [ast.literal_eval(p) for p in paths]

print(len(paths))